import { type Session } from "next-auth"
import { SessionProvider } from "next-auth/react"
import { type AppType } from "next/app"
import Head from "next/head"
import "~/styles/globals.css"
import { api } from "~/utils/api"
import ProgressProvider from "nextjs-progressbar"
import nextSeoConfig from "next-seo.config"
import { DefaultSeo } from "next-seo"
import { Analytics } from "@vercel/analytics/react"
import nextFonts from "~/lib/fonts"
import { Toaster } from "~/components/Toaster"

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProgressProvider color='#979797' options={{}} />
      <DefaultSeo {...nextSeoConfig} />
      <SessionProvider session={session}>
        <main className={`${nextFonts} font-sans`}>
          <Component {...pageProps} />
        </main>
        <Toaster />
      </SessionProvider>
      <Analytics />
    </>
  )
}

export default api.withTRPC(MyApp)
