import { type Session } from "next-auth"
import { SessionProvider } from "next-auth/react"
import { type AppType } from "next/app"
import Head from "next/head"
import "~/styles/globals.css"
import { api } from "~/utils/api"
import ProgressProvider from "nextjs-progressbar"
import nextSeoConfig from "next-seo.config"
import { DefaultSeo } from "next-seo"
import { Poppins, Roboto_Mono } from "next/font/google"

const sans = Poppins({
  weight: ["300", "400", "500", "600", "800"],
  subsets: ["latin"],
  variable: "--font-sans",
})

const mono = Roboto_Mono({
  subsets: ["latin", "vietnamese"],
  variable: "--font-mono",
})

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  const fonts = sans.variable + " " + mono.variable
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProgressProvider
        color='#979797'
        startPosition={0.3}
        stopDelayMs={200}
        height={2}
        showOnShallow={true}
      />
      <DefaultSeo {...nextSeoConfig} />
      <SessionProvider session={session}>
        <main className={`${fonts} font-sans`}>
          <Component {...pageProps} />
        </main>
      </SessionProvider>
    </>
  )
}

export default api.withTRPC(MyApp)
